create table if not exists user(
id INT AUTO_INCREMENT PRIMARY KEY,
username VARCHAR(45) NOT NULL,
password VARCHAR(45) NOT NULL,
photo BLOB NULL,
city VARCHAR(45) NOT NULL,
email VARCHAR(45) NOT NULL
);

CREATE TABLE IF NOT EXISTS genre(
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(45) NOT NULL
);

CREATE TABLE IF NOT EXISTS artist(
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(45) NOT NULL
);

CREATE TABLE IF NOT EXISTS genre_artist(
genre_id INT NOT NULL,
artist_id INT NOT NULL,
FOREIGN KEY (artist_id) REFERENCES artist (id) ON DELETE RESTRICT ON UPDATE CASCADE,
FOREIGN KEY (genre_id) REFERENCES genre (id) ON DELETE RESTRICT ON UPDATE CASCADE,
PRIMARY KEY (artist_id, genre_id)
);

CREATE TABLE IF NOT EXISTS wall(
id INT AUTO_INCREMENT PRIMARY KEY,
user_id INT NOT NULL,
genre_id INT NOT NULL,
datetime DATETIME NOT NULL,
text TEXT NOT NULL,
photo BLOB NULL,
FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE RESTRICT ON UPDATE CASCADE,
FOREIGN KEY (genre_id) REFERENCES genre (id) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS user_genre(
user_id INT NOT NULL,
genre_id INT NOT NULL,
FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE RESTRICT ON UPDATE CASCADE,
FOREIGN KEY (genre_id) REFERENCES genre (id) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS user_artist(
user_id INT NOT NULL,
artist_id INT NOT NULL,
FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE RESTRICT ON UPDATE CASCADE,
FOREIGN KEY (artist_id) REFERENCES artist (id) ON DELETE RESTRICT ON UPDATE CASCADE
);