"""new_revision1

Revision ID: 512cda007dcb
Revises: 4a90c8b48d92
Create Date: 2022-03-24 11:36:49.105590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '512cda007dcb'
down_revision = '4a90c8b48d92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wall', sa.Column('title', sa.String(length=100), nullable=True))
    op.drop_constraint('wall_genre_id_fkey', 'wall', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('wall_genre_id_fkey', 'wall', 'genre', ['genre_id'], ['id'])
    op.drop_column('wall', 'title')
    # ### end Alembic commands ###
