"""revision

Revision ID: aa9516ed2ffd
Revises: d8bdc0de7cbc
Create Date: 2022-02-21 13:38:15.676520

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'aa9516ed2ffd'
down_revision = 'd8bdc0de7cbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'genre_id',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=250)),
               nullable=True)
    op.alter_column('user', 'artist_id',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=250)),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'artist_id',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=250)),
               nullable=False)
    op.alter_column('user', 'genre_id',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=250)),
               nullable=False)
    # ### end Alembic commands ###
